"""Add currency to property

Revision ID: b57cc344d1e3
Revises: 59285ed36399
Create Date: 2026-03-08 14:55:33.840448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57cc344d1e3'
down_revision = '59285ed36399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    op.execute("UPDATE properties SET currency = 'JMD' WHERE currency IS NULL")
    
    # Now alter column to be NOT NULL
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('currency', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
